export const COLLECTION = {
  ASSIGNMENTS: "Assignments",
  ASSIGNMENT_SUBMISSIONS: "AssignmentSubmissions",
  COURSES: "Courses",
  BUNDLES: "Bundles",
  COHORTS: "Cohorts",
  USERS: "Users",
  CARTS: "Carts",
  LESSONS: "Lessons",
  COUPONS: "Coupons",
  COUPON_USAGES: "CouponUsages",
  ORDERS: "Orders",
  TRANSACTIONS: "Transactions",
  COUNTERS: "Counters",
  LEARNING_PROGRESS: "LearningProgress",
  ENROLLMENTS: "Enrollments",
  KARMA_DAILY: "KarmaDaily",
  KARMA_RULES: "KarmaRules",
  IDEMPOTENCY: "Idempotency",
} as const;

export const ORDER_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export const TRANSACTION_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export const TRANSACTION_TYPE = {
  PAYMENT: "PAYMENT",
  REFUND: "REFUND",
} as const;

export const PAYMENT_PROVIDER = {
  RAZORPAY: "RAZORPAY",
} as const;

export const ENROLLMENT_STATUS = {
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  DROPPED: "DROPPED",
} as const;

export const ENROLLED_PROGRAM_TYPE = {
  COURSE: "COURSE",
  BUNDLE: "BUNDLE",
} as const;

export const USER_ROLE = {
  STUDENT: "STUDENT",
  TEACHER: "TEACHER",
  INSTRUCTOR: "INSTRUCTOR",
  ADMIN: "ADMIN",
} as const;

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SUSPENDED: "SUSPENDED",
} as const;

export const KARMA_CATEGORY = {
  LEARNING: "LEARNING",
  COMMUNITY: "COMMUNITY",
  SOCIAL: "SOCIAL",
} as const;

export const KARMA_BREAKDOWN_TYPE = {
  LEARNING: "LEARNING",
  ASSIGNMENT: "ASSIGNMENT",
  QUIZ: "QUIZ",
  COMMUNITY: "COMMUNITY",
  SOCIAL: "SOCIAL",
} as const;

export const LEARNING_ACTION = {
  LESSON_WATCH_TIME: "LESSON WATCH TIME",
  KARMA_BOOST_LESSON_POINTS: "KARMA BOOST LESSON POINTS",
  LESSON_COMPLETION: "LESSON COMPLETION",
  ASSIGNMENT_SUBMISSION_MISS: "ASSIGNMENT SUBMISSION MISS",
  ASSIGNMENT_GRADE_FAIL: "ASSIGNMENT GRADE FAIL",
  ASSIGNMENT_GRADE_PASS: "ASSIGNMENT GRADE PASS",
  ASSIGNMENT_GRADE_90_PLUS: "ASSIGNMENT GRADE 90%+",
  QUIZ_MISSED: "QUIZ MISSED",
  QUIZ_GRADE_FAIL: "QUIZ GRADE FAIL",
  QUIZ_GRADE_PASS: "QUIZ GRADE PASS",
  QUIZ_GRADE_90_PLUS: "QUIZ GRADE 90%+",
} as const;

export const COMMUNITY_ACTION = {
  LESSON_COMMENT_APPROVED: "LESSON COMMENT (APPROVED)",
  FORUM_MESSAGE_APPROVED: "FORUM MESSAGE (APPROVED)",
  USER_UPVOTE_RECEIVED: "USER UPVOTE RECEIVED",
  USER_COMMENT_UNUPVOTED: "USER COMMENT UNUPVOTED",
  ADMIN_UPVOTE_RECEIVED: "ADMIN UPVOTE RECEIVED",
  MESSAGE_OR_COMMENT_REJECTED: "MESSAGE OR COMMENT REJECTED",
} as const;

export const SOCIAL_ACTION = {
  CERTIFICATE_SHARED: "CERTIFICATE SHARED",
} as const;
