export const USER_ROLE = {
    STUDENT: 'STUDENT',
    TEACHER: 'TEACHER',
    INSTRUCTOR: 'INSTRUCTOR',
    ADMIN: 'ADMIN'
} as const;

export const LESSON_TYPE = {
    SLIDE_DECK: 'SLIDE DECK',
    VIDEO_LECTURE: 'VIDEO LECTURE',
    ASSIGNMENT: 'ASSIGNMENT',
    QUIZ: 'QUIZ',
    INTERACTIVE_PROJECT: 'INTERACTIVE PROJECT'
} as const;

export const VIDEO_SOURCE = {
    YOUTUBE: 'YOUTUBE',
    VIMEO: 'VIMEO',
    UPLOAD: 'UPLOAD',
    EXTERNAL: 'EXTERNAL'
} as const;

export const ATTACHMENT_TYPE = {
    VIDEO: 'VIDEO',
    AUDIO: 'AUDIO',
    IMAGE: 'IMAGE',
    DOCUMENT: 'DOCUMENT'
} as const;

export const RESOURCE_TYPE = {
    FILE: 'FILE',
    LINK: 'LINK'
} as const;

export const COURSE_PROGRESS_STATUS = {
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
} as const;

export const LESSON_PROGRESS_STATUS = {
    NOT_STARTED: 'NOT STARTED',
    IN_PROGRESS: 'IN PROGRESS',
    COMPLETED: 'COMPLETED'
} as const;

export const COURSE_STATUS = {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    ARCHIVED: 'ARCHIVED'
} as const;

export const BUNDLE_STATUS = {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    ARCHIVED: 'ARCHIVED'
} as const;

export const COURSE_DIFFICULTY_LEVEL = {
    BEGINNER: 'BEGINNER',
    INTERMEDIATE: 'INTERMEDIATE',
    ADVANCED: 'ADVANCED'
} as const;

export const PRICING_MODEL = {
    FREE: 'FREE',
    PAID: 'PAID'
} as const;

export const LESSON_SCOPE = {
    COURSE: 'COURSE',
    APP: 'APP'
} as const;

export const USER_STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    SUSPENDED: "SUSPENDED",
} as const;

export const ENROLLMENT_STATUS = {
    ACTIVE: "ACTIVE",
    COMPLETED: "COMPLETED",
    DROPPED: "DROPPED"
} as const;

export const ENROLLED_PROGRAM_TYPE = {
    COURSE: "COURSE",
    BUNDLE: "BUNDLE"
} as const;

export const PAYMENT_STATUS = {
    PENDING: "PENDING",
    PAID: "PAID",
    PARTIAL: "PARTIAL",
    FAILED: "FAILED",
    REFUNDED: "REFUNDED"
} as const;

export const PAYMENT_PROVIDER = {
    RAZORPAY: "RAZORPAY",
    PAYPAL: "PAYPAL"
} as const;

export const CURRENCY = {
    INR: "INR",
    USD: "USD"
} as const;

export const LEARNING_UNIT = {
    LESSON: "LESSON",
    TOPIC: "TOPIC",
    COHORT: "COHORT"
} as const;

export const ENVIRONMENT = {
    DEVELOPMENT: "DEVELOPMENT",
    SANDBOX: "SANDBOX",
    PRODUCTION: "PRODUCTION"
} as const;

export const TRANSACTION_STATUS = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    COMPLETED: "COMPLETED",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
    REFUNDED: "REFUNDED",
    EXPIRED: "EXPIRED",
    DISPUTED: "DISPUTED",
} as const;

export const PAYMENT_ATTEMPT_STATUS = {
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
    SUCCESS: "SUCCESS"
} as const;

export const TRANSACTION_TYPE = {
    PAYMENT: "PAYMENT",
    REFUND: "REFUND",
} as const;

export const REFUND_INITIATOR = {
    ADMIN: "ADMIN",
    SYSTEM: "SYSTEM"
} as const;

// --- PAYPAL WEBHOOK EVENTS ---

export const PAYPAL_WEBHOOK_EVENT = {
    PAYMENTS_V2: {
        PAYMENT_AUTHORIZATION_CREATED: "PAYMENT.AUTHORIZATION.CREATED",
        PAYMENT_AUTHORIZATION_VOIDED: "PAYMENT.AUTHORIZATION.VOIDED",
        PAYMENT_CAPTURE_DECLINED: "PAYMENT.CAPTURE.DECLINED",
        PAYMENT_CAPTURE_COMPLETED: "PAYMENT.CAPTURE.COMPLETED",
        PAYMENT_CAPTURE_PENDING: "PAYMENT.CAPTURE.PENDING",
        PAYMENT_CAPTURE_REFUNDED: "PAYMENT.CAPTURE.REFUNDED",
        PAYMENT_CAPTURE_REVERSED: "PAYMENT.CAPTURE.REVERSED",
    },
    PAYMENTS_V1: {
        PAYMENT_AUTHORIZATION_CREATED: "PAYMENT.AUTHORIZATION.CREATED",
        PAYMENT_AUTHORIZATION_VOIDED: "PAYMENT.AUTHORIZATION.VOIDED",
        PAYMENT_CAPTURE_COMPLETED: "PAYMENT.CAPTURE.COMPLETED",
        PAYMENT_CAPTURE_DENIED: "PAYMENT.CAPTURE.DENIED",
        PAYMENT_CAPTURE_PENDING: "PAYMENT.CAPTURE.PENDING",
        PAYMENT_CAPTURE_REFUNDED: "PAYMENT.CAPTURE.REFUNDED",
        PAYMENT_CAPTURE_REVERSED: "PAYMENT.CAPTURE.REVERSED",
    },
    BATCH_PAYOUTS: {
        PAYMENT_PAYOUTSBATCH_DENIED: "PAYMENT.PAYOUTSBATCH.DENIED",
        PAYMENT_PAYOUTSBATCH_PROCESSING: "PAYMENT.PAYOUTSBATCH.PROCESSING",
        PAYMENT_PAYOUTSBATCH_SUCCESS: "PAYMENT.PAYOUTSBATCH.SUCCESS",
        PAYMENT_PAYOUTS_ITEM_BLOCKED: "PAYMENT.PAYOUTS-ITEM.BLOCKED",
        PAYMENT_PAYOUTS_ITEM_CANCELED: "PAYMENT.PAYOUTS-ITEM.CANCELED",
        PAYMENT_PAYOUTS_ITEM_DENIED: "PAYMENT.PAYOUTS-ITEM.DENIED",
        PAYMENT_PAYOUTS_ITEM_FAILED: "PAYMENT.PAYOUTS-ITEM.FAILED",
        PAYMENT_PAYOUTS_ITEM_HELD: "PAYMENT.PAYOUTS-ITEM.HELD",
        PAYMENT_PAYOUTS_ITEM_REFUNDED: "PAYMENT.PAYOUTS-ITEM.REFUNDED",
        PAYMENT_PAYOUTS_ITEM_RETURNED: "PAYMENT.PAYOUTS-ITEM.RETURNED",
        PAYMENT_PAYOUTS_ITEM_SUCCEEDED: "PAYMENT.PAYOUTS-ITEM.SUCCEEDED",
        PAYMENT_PAYOUTS_ITEM_UNCLAIMED: "PAYMENT.PAYOUTS-ITEM.UNCLAIMED",
    },
    BILLING: {
        BILLING_PLAN_CREATED: "BILLING.PLAN.CREATED",
        BILLING_PLAN_UPDATED: "BILLING.PLAN.UPDATED",
        BILLING_SUBSCRIPTION_CANCELLED: "BILLING.SUBSCRIPTION.CANCELLED",
        BILLING_SUBSCRIPTION_CREATED: "BILLING.SUBSCRIPTION.CREATED",
        BILLING_SUBSCRIPTION_REACTIVATED: "BILLING.SUBSCRIPTION.RE-ACTIVATED",
        BILLING_SUBSCRIPTION_SUSPENDED: "BILLING.SUBSCRIPTION.SUSPENDED",
        BILLING_SUBSCRIPTION_UPDATED: "BILLING.SUBSCRIPTION.UPDATED",
    },
    LOGIN: {
        IDENTITY_AUTHORIZATION_CONSENT_REVOKED: "IDENTITY.AUTHORIZATION-CONSENT.REVOKED",
    },
    CHECKOUT: {
        PAYMENTS_PAYMENT_CREATED: "PAYMENTS.PAYMENT.CREATED",
        CHECKOUT_ORDER_APPROVED: "CHECKOUT.ORDER.APPROVED",
        CHECKOUT_CHECKOUT_BUYER_APPROVED: "CHECKOUT.CHECKOUT.BUYER-APPROVED",
    },
    DISPUTES: {
        CUSTOMER_DISPUTE_CREATED: "CUSTOMER.DISPUTE.CREATED",
        CUSTOMER_DISPUTE_RESOLVED: "CUSTOMER.DISPUTE.RESOLVED",
        CUSTOMER_DISPUTE_UPDATED: "CUSTOMER.DISPUTE.UPDATED",
        RISK_DISPUTE_CREATED: "RISK.DISPUTE.CREATED",
    },
    INVOICING: {
        INVOICING_INVOICE_CANCELLED: "INVOICING.INVOICE.CANCELLED",
        INVOICING_INVOICE_CREATED: "INVOICING.INVOICE.CREATED",
        INVOICING_INVOICE_PAID: "INVOICING.INVOICE.PAID",
        INVOICING_INVOICE_REFUNDED: "INVOICING.INVOICE.REFUNDED",
        INVOICING_INVOICE_SCHEDULED: "INVOICING.INVOICE.SCHEDULED",
        INVOICING_INVOICE_UPDATED: "INVOICING.INVOICE.UPDATED",
    },
    MARKETPLACES: {
        CHECKOUT_ORDER_COMPLETED: "CHECKOUT.ORDER.COMPLETED",
        CHECKOUT_ORDER_APPROVED: "CHECKOUT.ORDER.APPROVED",
        CHECKOUT_ORDER_PROCESSED: "CHECKOUT.ORDER.PROCESSED",
        CUSTOMER_ACCOUNT_LIMITATION_ADDED: "CUSTOMER.ACCOUNT-LIMITATION.ADDED",
        CUSTOMER_ACCOUNT_LIMITATION_ESCALATED: "CUSTOMER.ACCOUNT-LIMITATION.ESCALATED",
        CUSTOMER_ACCOUNT_LIMITATION_LIFTED: "CUSTOMER.ACCOUNT-LIMITATION.LIFTED",
        CUSTOMER_ACCOUNT_LIMITATION_UPDATED: "CUSTOMER.ACCOUNT-LIMITATION.UPDATED",
        CUSTOMER_MERCHANT_INTEGRATION_CAPABILITY_UPDATED: "CUSTOMER.MERCHANT-INTEGRATION.CAPABILITY-UPDATED",
        CUSTOMER_MERCHANT_INTEGRATION_PRODUCT_SUBSCRIPTION_UPDATED: "CUSTOMER.MERCHANT-INTEGRATION.PRODUCT-SUBSCRIPTION-UPDATED",
        CUSTOMER_MERCHANT_INTEGRATION_SELLER_ALREADY_INTEGRATED: "CUSTOMER.MERCHANT-INTEGRATION.SELLER-ALREADY-INTEGRATED",
        CUSTOMER_MERCHANT_INTEGRATION_SELLER_ONBOARDING_INITIATED: "CUSTOMER.MERCHANT-INTEGRATION.SELLER-ONBOARDING-INITIATED",
        CUSTOMER_MERCHANT_INTEGRATION_SELLER_CONSENT_GRANTED: "CUSTOMER.MERCHANT-INTEGRATION.SELLER-CONSENT-GRANTED",
        CUSTOMER_MERCHANT_INTEGRATION_SELLER_EMAIL_CONFIRMED: "CUSTOMER.MERCHANT-INTEGRATION.SELLER-EMAIL-CONFIRMED",
        MERCHANT_ONBOARDING_COMPLETED: "MERCHANT.ONBOARDING.COMPLETED",
        MERCHANT_PARTNER_CONSENT_REVOKED: "MERCHANT.PARTNER-CONSENT.REVOKED",
        PAYMENT_CAPTURE_COMPLETED: "PAYMENT.CAPTURE.COMPLETED",
        PAYMENT_CAPTURE_DENIED: "PAYMENT.CAPTURE.DENIED",
        PAYMENT_CAPTURE_REFUNDED: "PAYMENT.CAPTURE.REFUNDED",
        PAYMENT_REFERENCED_PAYOUT_ITEM_COMPLETED: "PAYMENT.REFERENCED-PAYOUT-ITEM.COMPLETED",
        PAYMENT_REFERENCED_PAYOUT_ITEM_FAILED: "PAYMENT.REFERENCED-PAYOUT-ITEM.FAILED",
    },
    MERCHANT: {
        MERCHANT_ONBOARDING_COMPLETED: "MERCHANT.ONBOARDING.COMPLETED",
        MERCHANT_PARTNER_CONSENT_REVOKED: "MERCHANT.PARTNER-CONSENT.REVOKED",
        CUSTOMER_MANAGED_ACCOUNT_ACCOUNT_CREATED: "CUSTOMER.MANAGED-ACCOUNT.ACCOUNT-CREATED",
        CUSTOMER_MANAGED_ACCOUNT_CREATION_FAILED: "CUSTOMER.MANAGED-ACCOUNT.CREATION-FAILED",
        CUSTOMER_MANAGED_ACCOUNT_ACCOUNT_UPDATED: "CUSTOMER.MANAGED-ACCOUNT.ACCOUNT-UPDATED",
        CUSTOMER_MANAGED_ACCOUNT_ACCOUNT_STATUS_CHANGED: "CUSTOMER.MANAGED-ACCOUNT.ACCOUNT-STATUS-CHANGED",
        CUSTOMER_MANAGED_ACCOUNT_RISK_ASSESSED: "CUSTOMER.MANAGED-ACCOUNT.RISK-ASSESSED",
        CUSTOMER_MANAGED_ACCOUNT_NEGATIVE_BALANCE_NOTIFIED: "CUSTOMER.MANAGED-ACCOUNT.NEGATIVE-BALANCE-NOTIFIED",
        CUSTOMER_MANAGED_ACCOUNT_NEGATIVE_BALANCE_DEBIT_INITIATED: "CUSTOMER.MANAGED-ACCOUNT.NEGATIVE-BALANCE-DEBIT-INITIATED",
        CUSTOMER_ACCOUNT_LIMITATION_ADDED: "CUSTOMER.ACCOUNT-LIMITATION.ADDED",
        CUSTOMER_ACCOUNT_LIMITATION_LIFTED: "CUSTOMER.ACCOUNT-LIMITATION.LIFTED",
        CUSTOMER_ACCOUNT_LIMITATION_UPDATED: "CUSTOMER.ACCOUNT-LIMITATION.UPDATED",
        CUSTOMER_ACCOUNT_LIMITATION_ESCALATED: "CUSTOMER.ACCOUNT-LIMITATION.ESCALATED",
    },
    ORDERS_V2: {
        CHECKOUT_ORDER_COMPLETED: "CHECKOUT.ORDER.COMPLETED",
        CHECKOUT_ORDER_APPROVED: "CHECKOUT.ORDER.APPROVED",
        CHECKOUT_PAYMENT_APPROVAL_REVERSED: "CHECKOUT.PAYMENT-APPROVAL.REVERSED",
    },
    PAYMENT_ORDERS: {
        PAYMENT_ORDER_CANCELLED: "PAYMENT.ORDER.CANCELLED",
        PAYMENT_ORDER_CREATED: "PAYMENT.ORDER.CREATED",
    },
    REFERENCED_PAYOUTS: {
        PAYMENT_REFERENCED_PAYOUT_ITEM_COMPLETED: "PAYMENT.REFERENCED-PAYOUT-ITEM.COMPLETED",
        PAYMENT_REFERENCED_PAYOUT_ITEM_FAILED: "PAYMENT.REFERENCED-PAYOUT-ITEM.FAILED",
    },
    SALES: {
        PAYMENT_SALE_COMPLETED: "PAYMENT.SALE.COMPLETED",
        PAYMENT_SALE_DENIED: "PAYMENT.SALE.DENIED",
        PAYMENT_SALE_PENDING: "PAYMENT.SALE.PENDING",
        PAYMENT_SALE_REFUNDED: "PAYMENT.SALE.REFUNDED",
        PAYMENT_SALE_REVERSED: "PAYMENT.SALE.REVERSED",
    },
    SUBSCRIPTIONS: {
        CATALOG_PRODUCT_CREATED: "CATALOG.PRODUCT.CREATED",
        CATALOG_PRODUCT_UPDATED: "CATALOG.PRODUCT.UPDATED",
        PAYMENT_SALE_COMPLETED: "PAYMENT.SALE.COMPLETED",
        PAYMENT_SALE_REFUNDED: "PAYMENT.SALE.REFUNDED",
        PAYMENT_SALE_REVERSED: "PAYMENT.SALE.REVERSED",
        BILLING_PLAN_CREATED: "BILLING.PLAN.CREATED",
        BILLING_PLAN_UPDATED: "BILLING.PLAN.UPDATED",
        BILLING_PLAN_ACTIVATED: "BILLING.PLAN.ACTIVATED",
        BILLING_PLAN_PRICING_CHANGE_ACTIVATED: "BILLING.PLAN.PRICING-CHANGE.ACTIVATED",
        BILLING_PLAN_DEACTIVATED: "BILLING.PLAN.DEACTIVATED",
        BILLING_SUBSCRIPTION_CREATED: "BILLING.SUBSCRIPTION.CREATED",
        BILLING_SUBSCRIPTION_ACTIVATED: "BILLING.SUBSCRIPTION.ACTIVATED",
        BILLING_SUBSCRIPTION_UPDATED: "BILLING.SUBSCRIPTION.UPDATED",
        BILLING_SUBSCRIPTION_EXPIRED: "BILLING.SUBSCRIPTION.EXPIRED",
        BILLING_SUBSCRIPTION_CANCELLED: "BILLING.SUBSCRIPTION.CANCELLED",
        BILLING_SUBSCRIPTION_SUSPENDED: "BILLING.SUBSCRIPTION.SUSPENDED",
        BILLING_SUBSCRIPTION_PAYMENT_FAILED: "BILLING.SUBSCRIPTION.PAYMENT.FAILED",
    },
    PAYMENT_METHOD_TOKENS: {
        VAULT_PAYMENT_TOKEN_CREATED: "VAULT.PAYMENT-TOKEN.CREATED",
        VAULT_PAYMENT_TOKEN_DELETED: "VAULT.PAYMENT-TOKEN.DELETED",
        VAULT_PAYMENT_TOKEN_DELETION_INITIATED: "VAULT.PAYMENT-TOKEN.DELETION-INITIATED",
    },
} as const;

// --- RAZORPAY WEBHOOK EVENTS

export const RAZORPAY_WEBHOOK_EVENT = {
    PAYMENTS: {
        PAYMENT_AUTHORIZED: "payment.authorized",
        PAYMENT_CAPTURED: "payment.captured",
        PAYMENT_FAILED: "payment.failed",
    },
    ORDERS: {
        ORDER_PAID: "order.paid",
    },
    VIRTUAL_ACCOUNTS: {
        VIRTUAL_ACCOUNT_CREATED: "virtual_account.created",
        VIRTUAL_ACCOUNT_CREDITED: "virtual_account.credited",
    },
} as const;

// --- COUPON SYSTEM ---

export const COUPON_STATUS = {
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE",
    EXPIRED: "EXPIRED"
} as const;

export const COLLECTION = {
    COURSES: 'Courses',
    BUNDLES: 'Bundles',
    COHORTS: 'Cohorts',
    USERS: 'Users',
    LESSONS: 'Lessons',
    COUPONS: 'Coupons',
    COUPON_USAGES: 'CouponUsages',
    ORGANIZATIONS: 'Organizations',
    CONFIG: 'Config',
    ATTRIBUTES: 'Attributes',
} as const;

export const ATTRIBUTE_TYPE = {
    CATEGORY: "CATEGORY",
    TARGET_AUDIENCE: "TARGET AUDIENCE",
} as const;

export const ORGANIZATION = {
    SCHOOL: 'SCHOOL',
    INDUSTRY: 'INDUSTRY',
    COLLEGE: 'COLLEGE',
} as const;

export const CONFIG_DOCS = {
    PAYPAL_ACCESS_TOKEN: 'paypal_access_token',
} as const;