name: Deploy staging (dev creds)

on:
  push:
    branches:
      - staging

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: npm ci

      - name: Install Functions dependencies
        run: |
          cd functions
          npm ci

      - name: Build
        run: npm run build:dev
        env:
          VITE_VERIFY_RECAPTCHA_URL: ${{ vars.VITE_VERIFY_RECAPTCHA_URL }}
          VITE_RECAPTCHA_SITE_KEY: ${{ vars.VITE_RECAPTCHA_SITE_KEY }}
          VITE_API_KEY_FIREBASE: ${{ vars.VITE_API_KEY_FIREBASE }}
          VITE_AUTH_DOMAIN: ${{ vars.VITE_AUTH_DOMAIN }}
          VITE_PROJECT_ID: ${{ vars.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ vars.VITE_STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID: ${{ vars.VITE_MESSAGING_SENDER_ID }}
          VITE_APP_ID: ${{ vars.VITE_APP_ID }}
          VITE_RAZORPAY_KEY_ID: ${{ vars.VITE_RAZORPAY_KEY_ID }}
          VITE_PAYPAL_SANDBOX_CLIENT_ID: ${{ vars.VITE_PAYPAL_SANDBOX_CLIENT_ID }}
          VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}

      - name: Authenticate to GCP (dev)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.VITE_PROJECT_ID }}

      - name: Deploy to Firebase (dev)
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.GCP_SA_KEY_DEV }}
          PROJECT_ID: ${{ vars.VITE_PROJECT_ID }}
        run: firebase deploy --project $PROJECT_ID --only hosting,functions --non-interactive
